export const ARTICLE_ASSET_HARD_RULE = {
  version: "v3",
  mode: "exact" as const,
  cover_exact: 1,
  inline_exact: 3,
  total_exact: 4,
  required_ids: ["cover", "img-01", "img-02", "img-03"] as const,
  required_inline_ids: ["img-01", "img-02", "img-03"] as const,
  asset_policy: {
    mode: "exact",
    cover: {
      count: 1,
      engine: "chatgpt_images",
      aspect: "16:9",
      min_width: 1536,
      min_height: 864,
      text: "forbidden",
    },
    inline: {
      count: 3,
      engine: "chatgpt_images",
      min_width: 1280,
      min_height: 720,
    },
    required_ids: ["cover", "img-01", "img-02", "img-03"],
  },
  sequence: ["cover", "img-01", "img-02", "img-03"] as const,
  upload_tool: "upload_generated_image_file",
  external_upload_tool: "start_image_upload",
  svg_tool: "generate_and_upload_blog_image",
  never: [
    "Hub OpenAI Images API",
    "FLUX",
    "MCP image_base64",
    "SVG for cover/scene",
    "WebP thumbnail",
    "create_blog_draft before 4 RAW URLs",
    "stop because image_gen is missing from the MCP tool list",
  ],
  text: "ARTICLE_ASSET_HARD_RULE_V3. Resumable ChatGPT lane: start_article_workflow returns the cover prompt. On each user 'Tiếp tục', continue_article_workflow receives the previous native image file; the host supplies download_url + file_id. It uploads the image and returns the next prompt. Sequence cover→img-01→img-02→img-03; never parallel. After img-03 the workflow creates the draft. Never use base64, Hub OpenAI API, FLUX, start_image_upload, or SVG for scenes; start_image_upload is external-client only.",
} as const;
