export const ARTICLE_ASSET_HARD_RULE = {
  version: "v5",
  mode: "exact" as const,
  cover_exact: 1,
  inline_exact: 3,
  total_exact: 4,
  required_ids: ["cover", "img-01", "img-02", "img-03"] as const,
  required_inline_ids: ["img-01", "img-02", "img-03"] as const,
  asset_policy: {
    mode: "exact",
    cover: {
      count: 1,
      engine: "chatgpt_images",
      aspect: "16:9",
      min_width: 1536,
      min_height: 864,
      text: "forbidden",
    },
    inline: {
      count: 3,
      engine: "chatgpt_images",
      min_width: 1280,
      min_height: 720,
    },
    required_ids: ["cover", "img-01", "img-02", "img-03"],
  },
  sequence: ["cover", "img-01", "img-02", "img-03"] as const,
  upload_tool: "upload_generated_image_file",
  external_upload_tool: "start_image_upload",
  svg_tool: "generate_and_upload_blog_image",
  never: [
    "Hub OpenAI Images API",
    "FLUX",
    "MCP image_base64",
    "SVG for cover/scene",
    "WebP thumbnail",
    "gpt_scenes: direct create_blog_draft before 4 RAW URLs; only resumable workflow may create MEDIA_INCOMPLETE holders",
    "stop because image_gen is missing from the MCP tool list",
  ],
  text: "ARTICLE_ASSET_HARD_RULE_V5 applies only when article_mode=gpt_scenes. Resumable ChatGPT lane: start_article_workflow returns the cover prompt. On each user 'Tiếp tục', continue_article_workflow receives the previous native image file; the host supplies download_url + file_id. Sequence cover→img-01→img-02→img-03; never parallel. If generation/upload fails, call report_article_image_failure: retry once, then create a detailed holder and advance. After img-03 the workflow creates either a COMPLETE draft or a non-publishable MEDIA_INCOMPLETE draft. Never use base64, Hub OpenAI API, FLUX, start_image_upload, or SVG for scenes; start_image_upload is external-client only. Other article modes follow ARTICLE_MODE_ROUTING_V1.",
} as const;
