export const EDITORIAL_COMMANDS = {
  language: "vi-VN",
  rule: "Người dùng nói ngắn. Map đúng một việc mỗi tin. Không gộp viết tự do với viết theo tuần. Không publish, không duyệt tuần, không xóa bài.",
  status_vi: {
    proposed: "chờ duyệt",
    revision_requested: "đang chờ sửa / bài bị trả",
    revision_ready: "đã sửa, chờ xem lại",
    approved: "đã duyệt",
    writing: "đang viết",
    drafted: "chờ đọc bản nháp",
    published: "đã đăng — xong",
    cancelled: "đã hủy",
    blocked: "bị chặn vì tuần chưa duyệt cả tuần",
  },
  commands: [
    {
      id: "propose_week",
      hear: [
        "đề xuất lịch tuần",
        "lập lịch tuần này",
        "lập kế hoạch tuần",
        "đề xuất 3 bài",
        "đề xuất 4 bài",
        "đề xuất 5 bài",
        "lịch tuần sau",
      ],
      do: [
        "get_blog_inventory, get_blog_categories, list_editorial_weeks",
        "propose_editorial_week 3–5 bài, đủ rich brief",
        "Dừng. Báo week_id, status, từng title + ngày giờ. Bảo admin vào /admin/editorial",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "check_week_plan",
      hear: [
        "kiểm tra lịch tuần",
        "tuần này đã có kế hoạch chưa",
        "báo kế hoạch tuần",
        "báo trạng thái tuần",
        "check lịch tuần",
      ],
      do: [
        "list_editorial_weeks rồi get_editorial_week tuần gần nhất hoặc tuần user nêu",
        "Báo: title, status tiếng Việt, revision_number, khóa chưa, từng bài (title, ngày giờ, status)",
      ],
      never: ["create_blog_draft", "revise_editorial_week trừ khi được bảo sửa"],
    },
    {
      id: "report_week_detail",
      hear: [
        "báo lịch chi tiết",
        "báo chi tiết tuần",
        "liệt kê từng bài trong tuần",
        "đọc lại tuần",
      ],
      do: [
        "get_editorial_week",
        "Báo đủ: tóm tắt tuần, constraints, comments, diff nếu có, từng slot (id, title, ngày giờ, status, calendar_id, có draft chưa)",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "check_due_status",
      hear: [
        "bài nào đến hạn",
        "sắp đến hạn",
        "trễ hạn",
        "bị chặn",
        "check trạng thái bài",
        "check bài trong tuần",
      ],
      do: [
        "get_due_editorial_slots",
        "Báo 4 nhóm: due=đến hạn/trễ, upcoming=sắp đến, blocked=tuần chưa duyệt, revise=bài bị trả",
        "Chưa viết trừ khi user bảo viết",
      ],
      never: ["create_blog_draft trừ khi user bảo viết"],
    },
    {
      id: "revise_week_plan",
      hear: [
        "sửa",
        "sửa kế hoạch tuần",
        "revise tuần",
        "sửa lịch tuần",
        "sửa lịch",
        "đọc lại rồi sửa",
      ],
      do: [
        "get_editorial_week",
        "Đọc comments + revision_constraints + revision_number",
        "Nếu tuần proposed nhưng có slot revision_requested: vẫn gọi revise_editorial_week",
        "revise_editorial_week với based_on_revision đúng, gửi đủ 3 slot (kể cả bài không bị trả)",
        "Nếu REVISION_CONFLICT: get lại rồi sửa tiếp",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "free_write",
      hear: [
        "viết bài mới chế độ tự do",
        "viết bài tự do",
        "viết bài lẻ",
        "viết bài, nội dung là",
        "viết bài mới, nội dung là",
      ],
      do: [
        "get_editorial_guidelines, get_blog_inventory, get_blog_categories",
        "generate_and_upload_blog_image: cover + ít nhất 2 ảnh body",
        "create_blog_draft calendar_id=null task_id=null",
      ],
      never: ["propose_editorial_week", "calendar_id khác null"],
    },
    {
      id: "write_due_from_week",
      hear: [
        "kiểm tra tuần đã duyệt chưa, có bài đến hạn thì viết",
        "viết các bài đến hạn",
        "viết bài theo lịch tuần",
        "trễ hạn thì viết",
        "viết bài đến hạn hôm nay",
        "viết đúng 1 bài đến hạn",
      ],
      do: [
        "get_due_editorial_slots",
        "blocked[]: chỉ báo, không viết",
        "upcoming[]: chỉ báo, không viết",
        "due[]: viết, create_blog_draft với đúng calendar_id",
        "revise[]: xem command fix_rejected_draft / check_gpt_articles",
      ],
      never: ["calendar_id=null khi viết từ lịch", "viết upcoming hoặc blocked"],
    },
    {
      id: "write_one_slot",
      hear: [
        "viết đúng bài",
        "viết bài theo calendar_id",
        "chỉ viết 1 slot",
      ],
      do: [
        "get_editorial_week hoặc get_due_editorial_slots",
        "Chỉ 1 slot user nêu, phải nằm due[] hoặc đã Cho viết ngay",
        "create_blog_draft với calendar_id của slot đó",
      ],
      never: ["viết thêm bài khác", "calendar_id=null"],
    },
    {
      id: "fix_rejected_draft",
      hear: [
        "sửa bài bị trả",
        "check tuần có bài bị trả",
        "sửa draft",
        "update draft",
        "bài nào cần sửa",
        "kiểm tra bài ChatGPT đã viết",
        "bài nào đã đăng",
        "bài nào đang chờ đọc",
      ],
      do: [
        "list_editorial_articles — published/review/revise/writing",
        "revise: get_editorial_draft(calendar_id), đọc revision_request + comments",
        "Ảnh bìa/body: generate_and_upload_blog_image rồi gắn URL mới",
        "SEO/AIO: đạt seo_target nếu admin ghi, tối thiểu 95",
        "update_blog_draft(calendar_id). Không tạo bài mới",
      ],
      never: ["create_blog_draft cho cùng slot", "sửa bài published"],
    },
    {
      id: "regen_images",
      hear: ["tạo lại cover", "tạo lại ảnh", "đổi ảnh body"],
      do: [
        "generate_and_upload_blog_image",
        "Gắn URL mới vào featured_image / inline_images rồi mới create hoặc update draft",
      ],
      never: ["publish"],
    },
    {
      id: "use_existing_taxonomy",
      hear: ["gắn danh mục có sẵn", "đừng tạo danh mục mới", "dùng taxonomy hiện có"],
      do: ["get_blog_categories", "ưu tiên category_id có sẵn"],
      never: ["tạo category mới nếu đã có cái phù hợp"],
    },
  ],
  refuse: [
    "publish / đăng bài",
    "duyệt tuần / duyệt bài giúp tôi",
    "xóa bài / xóa tuần",
  ],
};
