export const EDITORIAL_COMMANDS = {
  language: "vi-VN",
  rule: "Người dùng chỉ cần nói 'Hãy viết bài về…', sau đó 'Tiếp tục nhé'. GPT research → start_article_workflow → tạo cover; mỗi lần Tiếp tục thì continue_article_workflow upload ảnh trước và trả prompt ảnh kế. Sau img-03 tự tạo draft. Không hỏi ID kỹ thuật. Không publish.",
  when_writing: {
    automatic: true,
    hard_rule: true,
    resumable: true,
    one_user_message: false,
    do_not_ask_for_technical_fields: true,
    lane_a: "start_article_workflow → cover. Mỗi lần user nói Tiếp tục: continue_article_workflow(file ảnh trước) → ảnh kế tiếp. Sau img-03 tự tạo draft.",
    cover: "16:9 ≥1536×864 không chữ. GPT tự đặt prompt ảnh.",
    body_exact: 3,
    body_min: 3,
    body_max: 3,
    body: "{{IMAGE:img-01}} … {{IMAGE:img-03}}, URL GitHub RAW.",
    lane_b: "workflow/rubric/timeline/bảng: generate_and_upload_blog_image SVG + required_labels tiếng Việt.",
    github: "Hub ghi quanpl86/imgBlog. Không image_base64 qua MCP.",
    if_no_image_gen:
      "image_gen KHÔNG phải tool MCP. ChatGPT Images là capability native trong chat. Tạo đúng ảnh mà next_action yêu cầu, sau đó chờ câu 'Tiếp tục' để bridge native file vào MCP.",
    never: [
      "generate_and_upload_blog_image cho cover/cảnh",
      "OpenAI Images API phía Hub",
      "FLUX",
      "image_base64 MCP",
      "nén WebP",
      "gửi draft khi còn thiếu URL ảnh",
    ],
  },
  status_vi: {
    proposed: "chờ duyệt",
    revision_requested: "đang chờ sửa / bài bị trả",
    revision_ready: "đã sửa, chờ xem lại",
    approved: "đã duyệt",
    writing: "đang viết",
    drafted: "chờ đọc bản nháp",
    published: "đã đăng — xong",
    cancelled: "đã hủy",
    blocked: "bị chặn vì tuần chưa duyệt cả tuần",
  },
  commands: [
    {
      id: "propose_week",
      hear: [
        "đề xuất lịch tuần",
        "lập lịch tuần này",
        "lập kế hoạch tuần",
        "đề xuất 3 bài",
        "đề xuất 4 bài",
        "đề xuất 5 bài",
        "lịch tuần sau",
      ],
      do: [
        "get_blog_inventory, get_blog_categories, list_editorial_weeks",
        "propose_editorial_week 3–5 bài, đủ rich brief",
        "Dừng. Báo week_id, status, từng title + ngày giờ. Bảo admin vào /admin/editorial",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "check_week_plan",
      hear: [
        "kiểm tra lịch tuần",
        "tuần này đã có kế hoạch chưa",
        "báo kế hoạch tuần",
        "báo trạng thái tuần",
        "check lịch tuần",
      ],
      do: [
        "list_editorial_weeks rồi get_editorial_week tuần gần nhất hoặc tuần user nêu",
        "Báo: title, status tiếng Việt, revision_number, khóa chưa, từng bài (title, ngày giờ, status)",
      ],
      never: ["create_blog_draft", "revise_editorial_week trừ khi được bảo sửa"],
    },
    {
      id: "report_week_detail",
      hear: [
        "báo lịch chi tiết",
        "báo chi tiết tuần",
        "liệt kê từng bài trong tuần",
        "đọc lại tuần",
      ],
      do: [
        "get_editorial_week",
        "Báo đủ: tóm tắt tuần, constraints, comments, diff nếu có, từng slot (id, title, ngày giờ, status, calendar_id, có draft chưa)",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "check_due_status",
      hear: [
        "bài nào đến hạn",
        "sắp đến hạn",
        "trễ hạn",
        "bị chặn",
        "check trạng thái bài",
        "check bài trong tuần",
      ],
      do: [
        "get_due_editorial_slots",
        "Báo 4 nhóm: due=đến hạn/trễ, upcoming=sắp đến, blocked=tuần chưa duyệt, revise=bài bị trả",
        "Chưa viết trừ khi user bảo viết",
      ],
      never: ["create_blog_draft trừ khi user bảo viết"],
    },
    {
      id: "revise_week_plan",
      hear: [
        "sửa",
        "sửa kế hoạch tuần",
        "revise tuần",
        "sửa lịch tuần",
        "sửa lịch",
        "đọc lại rồi sửa",
      ],
      do: [
        "get_editorial_week",
        "Đọc comments + revision_constraints + revision_number",
        "Nếu tuần proposed nhưng có slot revision_requested: vẫn gọi revise_editorial_week",
        "revise_editorial_week với based_on_revision đúng, gửi đủ 3 slot (kể cả bài không bị trả)",
        "Nếu REVISION_CONFLICT: get lại rồi sửa tiếp",
      ],
      never: ["create_blog_draft"],
    },
    {
      id: "free_write",
      hear: [
        "viết bài mới chế độ tự do",
        "viết bài tự do",
        "viết bài lẻ",
        "bài tự do",
        "blog tự do",
        "bài viết tự do",
        "viết blog tự do",
        "viết bài, nội dung là",
        "viết bài mới, nội dung là",
        "viết bài về",
      ],
      do: [
        "get_editorial_guidelines, get_blog_inventory, get_blog_categories, list_editorial_articles",
        "Nếu đã có nháp unpublished cùng chủ đề: tự chạy hết Lane A rồi update_blog_draft. Không hỏi user thêm. Không tạo bài trùng.",
        "Nếu chưa có nháp: tự chạy hết Lane A1 (4 ảnh tuần tự + native file params) rồi create_blog_draft calendar_id=null. Không hỏi user gõ prompt cover/upload.",
      ],
      never: [
        "propose_editorial_week",
        "create_blog_draft khi đã có nháp unpublished cùng chủ đề",
        "dừng giữa chừng để user gửi prompt cover/upload nếu image_gen đang có",
      ],
    },
    {
      id: "write_due_from_week",
      hear: [
        "kiểm tra tuần đã duyệt chưa, có bài đến hạn thì viết",
        "viết các bài đến hạn",
        "viết bài theo lịch tuần",
        "trễ hạn thì viết",
        "viết bài đến hạn hôm nay",
        "viết đúng 1 bài đến hạn",
      ],
      do: [
        "get_due_editorial_slots",
        "blocked[]: chỉ báo, không viết",
        "upcoming[]: chỉ báo, không viết",
        "due[]: when_writing (cover + 3 ảnh body ChatGPT Images, upload bằng native file params), rồi create_blog_draft với đúng calendar_id",
        "revise[]: xem command fix_rejected_draft / check_gpt_articles",
      ],
      never: ["calendar_id=null khi viết từ lịch", "viết upcoming hoặc blocked"],
    },
    {
      id: "write_one_slot",
      hear: [
        "viết đúng bài",
        "viết bài theo calendar_id",
        "chỉ viết 1 slot",
      ],
      do: [
        "get_editorial_week hoặc get_due_editorial_slots",
        "Chỉ 1 slot user nêu, phải nằm due[] hoặc đã Cho viết ngay",
        "when_writing: cover + 3 ảnh body ChatGPT Images, upload_generated_image_file, rồi create_blog_draft với calendar_id của slot đó",
      ],
      never: ["viết thêm bài khác", "calendar_id=null"],
    },
    {
      id: "fix_rejected_draft",
      hear: [
        "sửa bài bị trả",
        "check tuần có bài bị trả",
        "sửa draft",
        "update draft",
        "bài nào cần sửa",
        "kiểm tra bài ChatGPT đã viết",
        "bài nào đã đăng",
        "bài nào đang chờ đọc",
      ],
      do: [
        "list_editorial_articles — published/review/revise/writing",
        "revise: get_editorial_draft(calendar_id), đọc revision_request + comments",
        "Ảnh bìa/body mờ: tạo lại PNG gốc ≥1536 (cover) rồi upload_blog_image — không nén WebP",
        "SEO/AIO: đạt seo_target nếu admin ghi, tối thiểu 95",
        "update_blog_draft(calendar_id). Không tạo bài mới",
      ],
      never: ["create_blog_draft cho cùng slot", "sửa bài published"],
    },
    {
      id: "regen_images",
      hear: [
        "tạo lại cover",
        "tạo lại ảnh",
        "đổi ảnh body",
        "tạo ảnh cho bài post",
        "tạo trực tiếp",
      ],
      do: [
        "Cover/minh họa: tạo bằng ChatGPT Images trong chat này, rồi truyền file attachment vào upload_generated_image_file. ChatGPT host tự điền download_url + file_id.",
        "ĐƯỢC upload lên GitHub quanpl86/imgBlog (token Hub). Cover ≥1536×864",
        "KHÔNG nén WebP, KHÔNG resize 800×450, KHÔNG dùng FLUX 1024×576 làm cover",
        "Không dùng base64, không dùng start_image_upload từ ChatGPT. start_image_upload chỉ dành cho browser/external client có khả năng POST binary.",
        "Rubric/workflow/timeline/bảng: generate_and_upload_blog_image + required_labels, SVG",
        "Chỉ khi user bắt Hub tự gen (không ảnh trong chat): generate_and_upload_blog_image không base64 — server fallback, có thể 429",
        "Gắn URL MỚI vào package. Không tái sử dụng URL cũ.",
      ],
      never: ["publish", "nén WebP 800x450", "giảm chất lượng để vừa tool call"],
    },
    {
      id: "use_existing_taxonomy",
      hear: ["gắn danh mục có sẵn", "đừng tạo danh mục mới", "dùng taxonomy hiện có"],
      do: ["get_blog_categories", "ưu tiên category_id có sẵn"],
      never: ["tạo category mới nếu đã có cái phù hợp"],
    },
  ],
  refuse: [
    "publish / đăng bài",
    "duyệt tuần / duyệt bài giúp tôi",
    "xóa bài / xóa tuần",
  ],
};
