import { PresetSize, DesignTemplate } from '@/types/design-studio';

export const CANVAS_PRESETS: PresetSize[] = [
  {
    name: 'Slide 16:9 (Full HD)',
    width: 1920,
    height: 1080,
    description: 'Bản trình chiếu bài giảng, màn hình TV, hội thảo',
    aspectRatio: '16:9',
  },
  {
    name: 'YouTube Thumbnail',
    width: 1280,
    height: 720,
    description: 'Ảnh bìa video bài giảng STEM & Robotics',
    aspectRatio: '16:9',
  },
  {
    name: 'Ảnh vuông (1:1)',
    width: 1080,
    height: 1080,
    description: 'Bài viết Facebook, Instagram, Avatar',
    aspectRatio: '1:1',
  },
  {
    name: 'Story / TikTok / Reels (9:16)',
    width: 1080,
    height: 1920,
    description: 'Video dọc, tin ngắn, infographic di động',
    aspectRatio: '9:16',
  },
  {
    name: 'Poster A4 Dọc',
    width: 1240,
    height: 1754,
    description: 'In ấn poster ngày hội STEM, thông báo',
    aspectRatio: '1:1.41',
  },
  {
    name: 'Facebook Cover',
    width: 1640,
    height: 924,
    description: 'Ảnh bìa fanpage trường học, câu lạc bộ',
    aspectRatio: '16:9',
  },
];

export const PRESET_TEMPLATES: DesignTemplate[] = [
  {
    id: 'stem-certificate',
    name: 'Giấy Chứng Nhận Sáng Tạo STEM',
    category: 'certificate',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '🏆',
    description: 'Bố cục cân đối chuẩn mẫu chứng nhận hoàn thành dự án khoa học',
    data: {
      background: '#09090b',
      objects: [
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: '#111827',
          stroke: '#eab308',
          strokeWidth: 4,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 56,
          top: 56,
          width: 1168,
          height: 608,
          fill: 'transparent',
          stroke: '#ca8a04',
          strokeWidth: 1.5,
          rx: 10,
          ry: 10,
          selectable: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'CHỨNG NHẬN SÁNG TẠO STEM',
          left: 140,
          top: 100,
          width: 1000,
          fontSize: 42,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#facc15',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'Chứng nhận học viên đã xuất sắc hoàn thành dự án Khoa học Máy tính & Robotics',
          left: 140,
          top: 175,
          width: 1000,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#94a3b8',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'NGUYỄN VĂN AN',
          left: 140,
          top: 250,
          width: 1000,
          fontSize: 54,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#38bdf8',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 440,
          top: 340,
          width: 400,
          height: 3,
          fill: '#38bdf8',
          selectable: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'Hạng mục: Sáng Chế Robot Cứu Hộ Tự Hành Thông Minh\nBan Tổ Chức CLB Robotics & AI — Năm học 2026',
          left: 140,
          top: 375,
          width: 1000,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#e2e8f0',
          textAlign: 'center',
          lineHeight: 1.5,
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '★ ★ ★ ★ ★',
          left: 140,
          top: 490,
          width: 1000,
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#eab308',
          textAlign: 'center',
          splitByGrapheme: false,
        },
      ],
    },
  },
  {
    id: 'robotics-championship-poster',
    name: 'Poster Giải Đấu Robotics STEM',
    category: 'robotics',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '🤖',
    description: 'Bố cục hiện đại phong cách Cyberpunk cho giải đấu robot',
    data: {
      background: '#090d16',
      objects: [
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: '#0f172a',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 80,
          top: 80,
          width: 260,
          height: 38,
          fill: '#10b98122',
          stroke: '#10b981',
          strokeWidth: 1.5,
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '★ STEM CHALLENGE 2026',
          left: 95,
          top: 88,
          width: 230,
          fontSize: 16,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#34d399',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'GIẢI ĐẤU ROBOTICS & SÁNG TẠO TRẺ',
          left: 80,
          top: 150,
          width: 780,
          fontSize: 48,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#ffffff',
          lineHeight: 1.2,
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'Khám phá thế giới sa bàn AI, lập trình vi điều khiển và chế tạo robot cứu hộ tương lai.',
          left: 80,
          top: 290,
          width: 720,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#94a3b8',
          lineHeight: 1.4,
          splitByGrapheme: false,
        },
        {
          type: 'circle',
          originX: 'left',
          originY: 'top',
          left: 880,
          top: 150,
          radius: 150,
          fill: '#064e3b44',
          stroke: '#10b981',
          strokeWidth: 2,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '🤖',
          left: 935,
          top: 195,
          width: 190,
          fontSize: 110,
          fontFamily: 'Arial',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 80,
          top: 480,
          width: 320,
          height: 64,
          fill: '#10b981',
          rx: 12,
          ry: 12,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'ĐĂNG KÝ THAM GIA NGAY',
          left: 80,
          top: 500,
          width: 320,
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#022c22',
          textAlign: 'center',
          splitByGrapheme: false,
        },
      ],
    },
  },
  {
    id: 'youtube-stem-thumbnail',
    name: 'YouTube Thumbnail STEM Video',
    category: 'thumbnail',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '⚡',
    description: 'Ảnh bìa kích thích tò mò cho bài giảng công nghệ',
    data: {
      background: '#030712',
      objects: [
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 60,
          top: 70,
          width: 300,
          height: 48,
          fill: '#ef4444',
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'HƯỚNG DẪN TỪ A-Z',
          left: 60,
          top: 82,
          width: 300,
          fontSize: 22,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'TỰ CHẾ ROBOT\nTRONG 30 PHÚT?',
          left: 60,
          top: 160,
          width: 850,
          fontSize: 72,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#facc15',
          lineHeight: 1.15,
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 60,
          top: 440,
          width: 540,
          height: 70,
          fill: '#1e293b',
          stroke: '#38bdf8',
          strokeWidth: 2,
          rx: 10,
          ry: 10,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '⚡ Lập trình Scratch & Mạch Arduino',
          left: 80,
          top: 460,
          width: 500,
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#38bdf8',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '🚀',
          left: 920,
          top: 200,
          width: 250,
          fontSize: 140,
          fontFamily: 'Arial',
          textAlign: 'center',
          splitByGrapheme: false,
        },
      ],
    },
  },
  {
    id: 'stem-science-fair-light',
    name: 'Poster Ngày Hội STEM (Theme Sáng)',
    category: 'stem',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '🌿',
    description: 'Bố cục phong cách thanh lịch, nền sáng hiện đại cho triển lãm trường học',
    data: {
      background: '#f8fafc',
      objects: [
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: '#ffffff',
          stroke: '#e2e8f0',
          strokeWidth: 2,
          rx: 20,
          ry: 20,
          selectable: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 80,
          top: 80,
          width: 260,
          height: 40,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 1.5,
          rx: 20,
          ry: 20,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '🌱 TRIỂN LÃM STEM 2026',
          left: 80,
          top: 90,
          width: 260,
          fontSize: 15,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#059669',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'NGÀY HỘI KHOA HỌC & SÁNG TẠO XANH',
          left: 80,
          top: 155,
          width: 820,
          fontSize: 46,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#0f172a',
          lineHeight: 1.2,
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'Trải nghiệm robotics tự hành, mô hình năng lượng tái tạo và giải pháp AI vì cộng đồng.',
          left: 80,
          top: 285,
          width: 780,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#475569',
          lineHeight: 1.4,
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          originX: 'left',
          originY: 'top',
          left: 80,
          top: 480,
          width: 300,
          height: 60,
          fill: '#059669',
          rx: 12,
          ry: 12,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: 'THAM GIA MIỄN PHÍ',
          left: 80,
          top: 498,
          width: 300,
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'circle',
          originX: 'left',
          originY: 'top',
          left: 920,
          top: 170,
          radius: 130,
          fill: '#f0fdf4',
          stroke: '#86efac',
          strokeWidth: 2,
        },
        {
          type: 'textbox',
          originX: 'left',
          originY: 'top',
          text: '🔬',
          left: 955,
          top: 205,
          width: 190,
          fontSize: 100,
          fontFamily: 'Arial',
          textAlign: 'center',
          splitByGrapheme: false,
        },
      ],
    },
  },
];

