import { PresetSize, DesignTemplate } from '@/types/design-studio';

export const CANVAS_PRESETS: PresetSize[] = [
  {
    name: 'Slide 16:9 (Full HD)',
    width: 1920,
    height: 1080,
    description: 'Bản trình chiếu bài giảng, màn hình TV, hội thảo',
    aspectRatio: '16:9',
  },
  {
    name: 'YouTube Thumbnail',
    width: 1280,
    height: 720,
    description: 'Ảnh bìa video bài giảng STEM & Robotics',
    aspectRatio: '16:9',
  },
  {
    name: 'Ảnh vuông (1:1)',
    width: 1080,
    height: 1080,
    description: 'Bài viết Facebook, Instagram, Avatar',
    aspectRatio: '1:1',
  },
  {
    name: 'Story / TikTok / Reels (9:16)',
    width: 1080,
    height: 1920,
    description: 'Video dọc, tin ngắn, infographic di động',
    aspectRatio: '9:16',
  },
  {
    name: 'Poster A4 Dọc',
    width: 1240,
    height: 1754,
    description: 'In ấn poster ngày hội STEM, thông báo',
    aspectRatio: '1:1.41',
  },
  {
    name: 'Facebook Cover',
    width: 1640,
    height: 924,
    description: 'Ảnh bìa fanpage trường học, câu lạc bộ',
    aspectRatio: '16:9',
  },
];

export const PRESET_TEMPLATES: DesignTemplate[] = [
  {
    id: 'robotics-championship-poster',
    name: 'Poster Giải Đấu Robotics STEM',
    category: 'robotics',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '🤖',
    description: 'Bố cục hiện đại phong cách Cyberpunk cho giải đấu robot',
    data: {
      background: '#090d16',
      objects: [
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: '#0f172a',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
        },
        {
          type: 'rect',
          left: 80,
          top: 80,
          width: 260,
          height: 38,
          fill: '#10b98122',
          stroke: '#10b981',
          strokeWidth: 1.5,
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          text: '★ STEM CHALLENGE 2026',
          left: 95,
          top: 88,
          width: 240,
          fontSize: 16,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#34d399',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          text: 'GIẢI ĐẤU ROBOTICS & SÁNG TẠO TRẺ',
          left: 80,
          top: 150,
          width: 800,
          fontSize: 48,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#ffffff',
          lineHeight: 1.2,
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          text: 'Khám phá thế giới sa bàn AI, lập trình vi điều khiển và chế tạo robot cứu hộ tương lai.',
          left: 80,
          top: 290,
          width: 720,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#94a3b8',
          lineHeight: 1.4,
          splitByGrapheme: false,
        },
        {
          type: 'circle',
          left: 880,
          top: 150,
          radius: 160,
          fill: '#064e3b44',
          stroke: '#10b981',
          strokeWidth: 2,
        },
        {
          type: 'textbox',
          text: '🤖',
          left: 975,
          top: 220,
          width: 150,
          fontSize: 110,
          fontFamily: 'Arial',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          left: 80,
          top: 480,
          width: 320,
          height: 64,
          fill: '#10b981',
          rx: 12,
          ry: 12,
        },
        {
          type: 'textbox',
          text: 'ĐĂNG KÝ THAM GIA NGAY',
          left: 80,
          top: 500,
          width: 320,
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#022c22',
          textAlign: 'center',
          splitByGrapheme: false,
        },
      ],
    },
  },
  {
    id: 'stem-certificate',
    name: 'Giấy Chứng Nhận Sáng Tạo STEM',
    category: 'certificate',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '🏆',
    description: 'Mẫu chứng nhận hoàn thành dự án Khoa học Máy tính',
    data: {
      background: '#09090b',
      objects: [
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: '#18181b',
          stroke: '#eab308',
          strokeWidth: 3,
          rx: 12,
          ry: 12,
        },
        {
          type: 'rect',
          left: 55,
          top: 55,
          width: 1170,
          height: 610,
          fill: 'transparent',
          stroke: '#eab30844',
          strokeWidth: 1.5,
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          text: 'CHỨNG NHẬN SÁNG TẠO STEM',
          left: 140,
          top: 110,
          width: 1000,
          fontSize: 42,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#facc15',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          text: 'Chứng nhận học viên đã xuất sắc hoàn thành xuất sắc dự án khoa học thực nghiệm',
          left: 140,
          top: 180,
          width: 1000,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#a1a1aa',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          text: 'NGUYỄN VĂN AN',
          left: 140,
          top: 260,
          width: 1000,
          fontSize: 54,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#38bdf8',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          left: 390,
          top: 345,
          width: 500,
          height: 3,
          fill: '#38bdf8',
        },
        {
          type: 'textbox',
          text: 'Hạng mục: Sáng Chế Robot Cứu Hộ Tự Hành Thông Minh\nBan Tổ Chức CLB Robotics & AI — Năm học 2026',
          left: 140,
          top: 380,
          width: 1000,
          fontSize: 22,
          fontFamily: 'Inter',
          fill: '#e4e4e7',
          textAlign: 'center',
          lineHeight: 1.5,
          splitByGrapheme: false,
        },
      ],
    },
  },
  {
    id: 'youtube-stem-thumbnail',
    name: 'YouTube Thumbnail STEM Video',
    category: 'thumbnail',
    dimensions: { width: 1280, height: 720 },
    thumbnail: '⚡',
    description: 'Ảnh bìa kích thích tò mò cho bài giảng công nghệ',
    data: {
      background: '#030712',
      objects: [
        {
          type: 'rect',
          left: 60,
          top: 80,
          width: 300,
          height: 48,
          fill: '#ef4444',
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          text: 'HƯỚNG DẪN TỪ A-Z',
          left: 60,
          top: 92,
          width: 300,
          fontSize: 22,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          splitByGrapheme: false,
        },
        {
          type: 'textbox',
          text: 'TỰ CHẾ ROBOT\nTRONG 30 PHÚT?',
          left: 60,
          top: 170,
          width: 800,
          fontSize: 72,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#facc15',
          lineHeight: 1.15,
          splitByGrapheme: false,
        },
        {
          type: 'rect',
          left: 60,
          top: 420,
          width: 540,
          height: 70,
          fill: '#1e293b',
          stroke: '#38bdf8',
          strokeWidth: 2,
          rx: 10,
          ry: 10,
        },
        {
          type: 'textbox',
          text: '⚡ Lập trình Scratch & Mạch Arduino',
          left: 80,
          top: 440,
          width: 500,
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#38bdf8',
          splitByGrapheme: false,
        },
      ],
    },
  },
];
