import { BookOpenCheck, BrainCircuit, Cpu, Palette } from 'lucide-react';

export const knowledgeFields = [
  {
    slug: 'eng-tech',
    label: 'Kỹ thuật & Công nghệ',
    eyebrow: 'Kỹ thuật & Công nghệ',
    description: 'Xây dựng, thử nghiệm và làm chủ những hệ thống định hình tương lai.',
    subjects: ['AI', 'Robot', 'Phần mềm', 'STEM'],
    categories: ['artificial-intelligence', 'ai-in-education', 'robotics-hardware', 'competition-robotics', 'fullstack-development', 'stem-education'],
    icon: Cpu,
    accent: 'orange',
  },
  {
    slug: 'edu-skills',
    label: 'Giáo dục & Kỹ năng',
    eyebrow: 'Giáo dục & Kỹ năng',
    description: 'Phương pháp, công cụ và kinh nghiệm thực hành dành cho giáo viên và người làm giáo dục.',
    subjects: ['Phương pháp dạy học', 'Đánh giá học tập', 'Giáo dục mầm non'],
    categories: ['project-based-learning', 'instructional-models', 'teacher-development', 'learning-assessment', 'early-childhood-education'],
    icon: BookOpenCheck,
    accent: 'emerald',
  },
  {
    slug: 'sciences',
    label: 'Khoa học',
    eyebrow: 'Khoa học',
    description: 'Khám phá tư duy máy tính, thuật toán và khoa học máy tính từ nền tảng đến ứng dụng.',
    subjects: ['Khoa học máy tính'],
    categories: ['scratch-block-coding', 'python-for-education', 'computer-science-education'],
    icon: BrainCircuit,
    accent: 'blue',
  },
  {
    slug: 'arts-creative',
    label: 'Nghệ thuật & Sáng tạo',
    eyebrow: 'Nghệ thuật & Sáng tạo',
    description: 'Thiết kế 3D và đa phương tiện để biến ý tưởng thành học liệu sống động.',
    subjects: ['Thiết kế 3D', 'Đa phương tiện'],
    categories: ['3d-design-printing', 'multimedia-for-learning'],
    icon: Palette,
    accent: 'violet',
  },
] as const;

const taxonomyLabelsBySlug: Record<string, string> = {
  'eng-tech': 'Kỹ thuật & Công nghệ',
  'edu-skills': 'Giáo dục & Kỹ năng',
  sciences: 'Khoa học',
  'arts-creative': 'Nghệ thuật & Sáng tạo',
  stem: 'STEM',
  ai: 'AI',
  robotics: 'Robot',
  software: 'Phần mềm',
  pedagogy: 'Phương pháp dạy học',
  assessment: 'Đánh giá học tập',
  'early-childhood': 'Giáo dục mầm non',
  'computer-science': 'Khoa học máy tính',
  '3d-design': 'Thiết kế 3D',
  multimedia: 'Đa phương tiện',
  'stem-education': 'Giáo dục STEM',
  'project-based-learning': 'Học tập qua dự án',
  'instructional-models': 'Mô hình dạy học',
  'early-childhood-education': 'Giáo dục mầm non',
  'teacher-development': 'Phát triển chuyên môn giáo viên',
  'artificial-intelligence': 'Trí tuệ nhân tạo',
  'ai-in-education': 'AI trong giáo dục',
  'generative-ai-tools': 'AI tạo sinh & Công cụ',
  'robotics-hardware': 'Robot & Phần cứng',
  'competition-robotics': 'Robot thi đấu',
  'fullstack-development': 'Phát triển ứng dụng web',
  'scratch-block-coding': 'Scratch & Lập trình khối',
  'python-for-education': 'Python trong giáo dục',
  'computer-science-education': 'Giáo dục khoa học máy tính',
  'learning-assessment': 'Đánh giá học tập',
  '3d-design-printing': 'Thiết kế & In 3D',
  'multimedia-for-learning': 'Đa phương tiện trong dạy học',
};

const taxonomyLabelsByName: Record<string, string> = {
  'Engineering & Technology': 'Kỹ thuật & Công nghệ',
  'Education & Skills': 'Giáo dục & Kỹ năng',
  Sciences: 'Khoa học',
  'Arts & Creative': 'Nghệ thuật & Sáng tạo',
  Robotics: 'Robot',
  Software: 'Phần mềm',
  Pedagogy: 'Phương pháp dạy học',
  Assessment: 'Đánh giá học tập',
  'Early Childhood': 'Giáo dục mầm non',
  'Computer Science': 'Khoa học máy tính',
  '3D Design': 'Thiết kế 3D',
  Multimedia: 'Đa phương tiện',
  'STEM Education': 'Giáo dục STEM',
  'Project-Based Learning': 'Học tập qua dự án',
  'Instructional Models': 'Mô hình dạy học',
  'Early Childhood Education': 'Giáo dục mầm non',
  'Teacher Development': 'Phát triển chuyên môn giáo viên',
  'Artificial Intelligence': 'Trí tuệ nhân tạo',
  'AI in Education': 'AI trong giáo dục',
  'Generative AI Tools': 'AI tạo sinh & Công cụ',
  'Robotics & Hardware': 'Robot & Phần cứng',
  'Competition Robotics': 'Robot thi đấu',
  'Full-stack Development': 'Phát triển ứng dụng web',
  'Scratch & Block Coding': 'Scratch & Lập trình khối',
  'Python for Education': 'Python trong giáo dục',
  'Computer Science Education': 'Giáo dục khoa học máy tính',
  'Learning Assessment': 'Đánh giá học tập',
  '3D Design & Printing': 'Thiết kế & In 3D',
  'Multimedia for Learning': 'Đa phương tiện trong dạy học',
};

export function getVietnameseTaxonomyLabel(name?: string | null, slug?: string | null) {
  if (slug && taxonomyLabelsBySlug[slug]) return taxonomyLabelsBySlug[slug];
  if (name && taxonomyLabelsByName[name]) return taxonomyLabelsByName[name];
  return name || 'Tri thức';
}
