-- 1. Tạo bảng Fields (Lớp cao nhất - Vệ tinh)
CREATE TABLE IF NOT EXISTS fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Cập nhật bảng Subjects để liên kết với Fields
ALTER TABLE subjects 
ADD COLUMN IF NOT EXISTS field_id BIGINT REFERENCES fields(id) ON DELETE SET NULL;

-- 3. Bật RLS cho bảng Fields
ALTER TABLE fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Fields viewable by everyone" ON fields FOR SELECT USING (true);

-- 4. Seed dữ liệu Fields mẫu
INSERT INTO fields (name, slug, description) VALUES
('Engineering & Technology', 'eng-tech', 'Các lĩnh vực kỹ thuật và công nghệ hiện đại'),
('Arts & Creative', 'arts-creative', 'Sáng tạo nội dung, thiết kế và nghệ thuật số'),
('Sciences', 'sciences', 'Khoa học cơ bản và ứng dụng'),
('Education & Skills', 'edu-skills', 'Phát triển kỹ năng và phương pháp giáo dục')
ON CONFLICT (slug) DO NOTHING;
