-- Thêm bảng Tags (Hệ thống thẻ linh hoạt)
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bảng trung gian Post-Tags (Nhiều bài viết - Nhiều thẻ)
CREATE TABLE IF NOT EXISTS post_tags (
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

-- Cập nhật bảng Posts với các trường Metadata STEM/Tech
ALTER TABLE posts 
ADD COLUMN IF NOT EXISTS difficulty_level TEXT, -- beginner, intermediate, advanced
ADD COLUMN IF NOT EXISTS primary_tool TEXT, -- e.g., Arduino, Python, Blender
ADD COLUMN IF NOT EXISTS estimate_time TEXT, -- e.g., 2 hours
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS series_name TEXT;

-- Bật RLS cho bảng mới
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;

-- Policies cho Tags
CREATE POLICY "Tags viewable by everyone" ON tags FOR SELECT USING (true);
CREATE POLICY "Post tags viewable by everyone" ON post_tags FOR SELECT USING (true);
