-- 1. Tạo bảng Subjects (Lớp cao nhất)
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  icon TEXT, -- Để hiển thị icon đại diện cho STEM, AI...
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Cập nhật bảng Categories để liên kết với Subjects
-- Lưu ý: Nếu đã có dữ liệu, cần cẩn thận khi thêm cột NOT NULL. Ở đây ta cho phép NULL ban đầu.
ALTER TABLE categories 
ADD COLUMN IF NOT EXISTS subject_id BIGINT REFERENCES subjects(id) ON DELETE SET NULL;

-- 3. Bật RLS cho bảng Subjects
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Subjects viewable by everyone" ON subjects FOR SELECT USING (true);

-- 4. Seed một số Subjects mặc định theo ý tưởng của bạn
INSERT INTO subjects (name, slug, description) VALUES
('STEM', 'stem', 'Science, Technology, Engineering, Math'),
('STEAM', 'steam', 'STEM with Arts integration'),
('ROBOTICS', 'robotics', 'Robot design and programming'),
('AI', 'ai', 'Artificial Intelligence & Machine Learning'),
('3D DESIGN', '3d-design', '3D Modeling and Printing'),
('MULTIMEDIA', 'multimedia', 'Digital Art and Media Production'),
('TECHNOLOGY', 'technology', 'General Tech and Development')
ON CONFLICT (slug) DO NOTHING;
